# Generated by Django 3.1.6 on 2021-09-30 10:18

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_auto_20210929_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_img',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\USER\\Desktop\\studyy\\media'), upload_to='news/'),
        ),
    ]
