# Generated by Django 3.2.7 on 2021-09-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='text_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='title_az',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='title_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='title_ru',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='country_az',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='country_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='country_ru',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='location_az',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='location_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='location_ru',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
