# Generated by Django 3.2.7 on 2021-09-28 18:50

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('text', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage('/home/zaur/Study-pro/Study/media'), upload_to='education/')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImagesForGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(storage=django.core.files.storage.FileSystemStorage('/home/zaur/Study-pro/Study/media'), upload_to='guests/')),
            ],
        ),
    ]
