# Generated by Django 3.2.7 on 2021-09-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='text_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='title_az',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='title_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='title_ru',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='text_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='title_az',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='title_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='title_ru',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
