# Generated by Django 3.1.6 on 2021-09-30 10:18

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20210929_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='education',
            name='img',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage('C:\\Users\\USER\\Desktop\\studyy\\media'), upload_to='education/'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='imagesforguest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='imagesforguest',
            name='img',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage('C:\\Users\\USER\\Desktop\\studyy\\media'), upload_to='guests/'),
        ),
    ]
