# Generated by Django 3.2.7 on 2021-09-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='who_are_we_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='who_are_we_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detailsfeature',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='detailsfeature',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='detailsfeature',
            name='title_en',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='detailsfeature',
            name='title_ru',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='forworkpage',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='forworkpage',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='forworkpage',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='forworkpage',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
