# Generated by Django 3.2.7 on 2021-09-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0002_auto_20210928_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='who_are_we_az',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detailsfeature',
            name='text_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='detailsfeature',
            name='title_az',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='text_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='title_az',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='forworkpage',
            name='text_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='forworkpage',
            name='title_az',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='text_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_az',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
