# Generated by Django 3.2.7 on 2021-09-28 18:50

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_name', models.CharField(max_length=80)),
                ('uni_img', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/home/zaur/Study-pro/Study/media'), upload_to='university/')),
                ('uni_choices', models.CharField(choices=[('Özel', 'Özel'), ('Devlet', 'Devlet')], max_length=6)),
            ],
        ),
    ]
